---
- name: Install Nginx
  apt:
    pkg:
      - nginx
    state: latest
    update_cache: yes
  become: yes

- name: Set up Nginx conf file
  template:
    src: "templates/metabase.conf.j2"
    dest: "/etc/nginx/conf.d/metabase.conf"
  become: yes
  notify: Restart Nginx
